const {chromium}=require('playwright');const fs=require('fs');const assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({...(process.env.QA_BROWSER==='chromium'?{}:{channel:'msedge'}),headless:true});fs.mkdirSync('outputs',{recursive:true});const results=[];const base='http://127.0.0.1:8765/';
for(const [name,viewport] of [['desktop',{width:1440,height:900}],['mobile',{width:390,height:844}],['small',{width:320,height:568}],['landscape',{width:844,height:390}]]){
 const page=await browser.newPage({viewport});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('#pause').click();
 for(const [scene,time] of [['forest',1100],['title',3300],['museum',5800]]){await page.evaluate(t=>{document.getAnimations().forEach(a=>{a.pause();a.currentTime=t})},time);await page.screenshot({path:`outputs/${name}-${scene}.png`});const box=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,skip:document.querySelector('.skip').getBoundingClientRect().toJSON()}));assert(box.scroll<=box.width);assert(box.skip.x>=0&&box.skip.right<=box.width)}
 assert.equal(errors.length,0);results.push({test:name+' three scenes, overflow and JS errors',passed:true});await page.close();
}
async function timing(name,options={}){const ctx=await browser.newContext(options);const page=await ctx.newPage();let elapsed;await ctx.route('https://vishtynets.ru/**',async route=>{elapsed=Date.now()-start;await route.fulfill({body:'Destination intercepted for QA; museum not loaded',contentType:'text/html'})});const start=Date.now();await page.goto(base);await page.waitForURL('https://vishtynets.ru/',{timeout:10000});assert(elapsed>=6900&&elapsed<8000);results.push({test:name,elapsedMs:elapsed,passed:true});await ctx.close()}
await timing('real automatic redirect');await timing('reduced motion redirect',{reducedMotion:'reduce'});await timing('JavaScript disabled meta refresh',{javaScriptEnabled:false});
const page=await browser.newPage();await page.route('https://vishtynets.ru/**',r=>r.fulfill({body:'QA destination'}));await page.goto(base);await page.keyboard.press('Tab');assert.equal(await page.locator('.skip').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Tab');assert.equal(await page.locator('#pause').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Enter');await page.waitForTimeout(7200);assert(page.url().startsWith(base));await page.keyboard.press('Enter');await page.waitForURL('https://vishtynets.ru/',{timeout:8000});results.push({test:'keyboard focus, pause beyond 7s and resume',passed:true});
await page.goto(base);assert.equal(await page.locator('.skip').evaluate(e=>getComputedStyle(e).opacity),'1');await page.locator('.skip').click();await page.waitForURL('https://vishtynets.ru/');results.push({test:'skip visible immediately and navigates',passed:true});await page.close();
const reduced=await browser.newPage({reducedMotion:'reduce'});await reduced.goto(base);assert.equal(await reduced.evaluate(()=>document.getAnimations().length),0);assert.equal(await reduced.locator('.museum').evaluate(e=>getComputedStyle(e).opacity),'1');await reduced.screenshot({path:'outputs/reduced-motion.png'});results.push({test:'reduced motion static museum and zero animations',passed:true});await reduced.close();
fs.writeFileSync('outputs/qa-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
